baseURL = "http://www.ratheshprabakar.tech"
languageCode = "en-us"
theme = "rad"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Blog"
  URL = "https:///medium.com/@ratheshprabakar"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 5


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Blog"
  URL = "https:///medium.com/@ratheshprabakar"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 5


[params]

  [params.logo]
    text1 = "Rathesh"
    text2 = "Prabakar"

      
