baseURL = "https://www.ratheshprabakar.me"
languageCode = "en-us"
theme = "rad"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Blog"
  URL = "https://ratheshprabakar.me/blog"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "#footer"
  weight = 5


 


[params]

  [params.logo]
    text1 = "Rathesh"
    text2 = "Prabakar"

      
